" Syntax & filetype "
syntax on
filetype plugin indent on

" Highlight tab characters "
"highlight SpecialKey ctermfg=1
"set list
"set listchars=tab:T>

set nocompatible
set ruler
set mouse=a

" Colorscheme "
colorscheme wombat

" Column to denote max line length "
let &colorcolumn="80,".join(range(120,999),",")

" Tab setting "
set expandtab
set shiftwidth=2
set softtabstop=2
set number

" Indenting "
set backspace=indent,eol,start
set autoindent
set smartindent

" Clipboard "
set clipboard=unnamed

" Persistent Undo "
set undofile

" Directories for swap, undo and bak "
set dir=~/.vim/.swap
set undodir=~/.vim/.undo
set backupdir=~/.vim/.backup

" Folding Options "
set foldenable          " enable folding
set foldlevelstart=10   " fold levels to open by default
set foldnestmax=10      " max num of nested folds allowed
set foldmethod=indent   " there are like 6 other ways

" Key maps "
nnoremap <space> za

" Set cursor in vim modes "
let &t_SI = "\e[5 q"  " insert mode
let &t_EI = "\e[1 q"  " normal mode

" Install vim-plug + plugins "
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'tpope/vim-surround'
Plug 'airblade/vim-gitgutter'

call plug#end()

""" Plugin Related """
" gitgutter "
set updatetime=250
