" Pathogen "
execute pathogen#infect()

" Syntax & filetype "
syntax on
filetype plugin indent on
filetype plugin on

" Highlight tab characters "
highlight SpecialKey ctermfg=1
set list
set listchars=tab:T>

set nocompatible
set ruler
set mouse=a

" Let vim use the system clipboard by defaulti "
set clipboard=unnamedplus
" Preserve the clipboard on vim exit "
autocmd VimLeave * call system("xsel -ib", getreg('+'))

" Colorscheme "
colorscheme wombat

" Column to denote max line length "
let &colorcolumn="80,".join(range(120,999),",")

" Tab setting "
set expandtab
set shiftwidth=4
set softtabstop=4
set number

" Indenting "
set backspace=indent,eol,start
set autoindent

" Persistent Undo "
set undofile

" Directories for swap, undo and bak "
set dir=~/.vim/.swap
set undodir=~/.vim/.undo
set backupdir=~/.vim/.backup
