views:
  # Alters the pod view column layout. Uses GVR as key
  v1/pods:
    # Overrides default sort column
    sortColumn: AGE:desc
    columns:
      - "AGE"
      - "NAMESPACE"
      - "NAME"
      - "READY"
      - "STATUS"
      - "RESTARTS"
      - "PF|W"

  # Alters the service view column layout
  v1/services:
    sortColumn: AGE:desc
    columns:
      - "AGE"
